#MySQL Details
MySQL: # SQL Settings
  Host: "localhost"
  Port: "3306"
  Database: "vanquil"
  Username: "root"
  Password: ""

#Options for KillLevel
Settings:
  Starting Level: 0
  Starting EXP: 0
  Starting Kills: 0
